#!/bin/bash

export AWS_ACCESS_KEY_ID=foo
export AWS_SECRET_ACCESS_KEY=barf
export CDN_HOST='d3sfmd7z2ddzob.cloudfront.net'
export SECRET_TOKEN=foo
export APPLICATION_SECRET_KEY_BASE=foo
export REDIS_PROVIDER=R
export R='redis://localhost:6379'
export S3_BUCKET_NAME=upperhand-dev
export PATH="$PATH:~/.phantomjs/$(ls -1 ~/.phantomjs/ | tail -1 | tr -d "\n")/bin"
export JWT_ISSUER="Upper Hand"
export UH_TOLL_FREE="8005116236"

$*
