#!/bin/bash
#ln -s /path/to/original /path/to/symlink
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# after installing oh-my-zsh
ln -s $DIR/zsh/zshrc $ZSH/custom/aliases.zsh
ln -s $DIR/vim/vimrc ~/.vimrc
ln -s $DIR/ag/agignore ~/.agignore
ln -s $DIR/tmux/tmux.conf ~/.tmux.conf
ln -s $DIR/git/gitignore_global ~/.gitignore_global
ln -s $DIR/git/gitconfig ~/.gitconfig
ln -s $DIR/psql/psqlrc ~/.psqlrc
for i in $(ls $DIR/bin/); do
  ln -s $DIR/bin/$i ~/bin/$i
done
