
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

alias uh='cd ~/Repositories/upperhand/uh'
alias rs-uh='~/bin/upperhand-rails s'
alias rc-uh='~/bin/upperhand-rails c'
alias rk-uh='~/bin/upperhand-rake'

alias h='heroku'
alias hc='h run console -a'
alias qascale='h scale worker=1 scheduler=1 -a'
alias 0scale='h scale worker=0 scheduler=0 -a'
alias hsql='h pg:psql -a'
alias lsql='psql sh3_development'

alias tm='tmux'
alias tmn='tmux new -s'
alias tma='tmux a -t'

alias co='git checkout'
alias filediff=gitFileDiff
gitFileDiff() {
  git diff-tree --no-commit-id --name-only -r HEAD..$1
}

source ~/bin/git-completion.bash # run if not working

fpath=(~/.zsh $fpath)

