
export PATH="/usr/local/bin:$PATH" # use brew git
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

alias soa='source ~/.oh-my-zsh/custom/aliases.zsh'

alias z='zeus'

alias gco='git checkout'
alias gcob='git checkout -b'
alias gg='git log'
alias gl='git pull'
alias gai='git add . -p'
alias ga='git add'
alias gaa='git add --all'
alias gcm='git commit -m'
alias gc='git commit'
alias gh='git push'
alias gs='git status'
alias gd='git diff'
alias gsh='git stash'
alias gshl='git stash list'
alias gshp='git stash pop'

alias api_server='export LOCAL_AUTHENTICATION=true && rails s -p 3001 -b 0.0.0.0'
alias api_server_local_false='export LOCAL_AUTHENTICATION=false && rails s -p 3001 -b 0.0.0.0'
alias fe_server='rails s'

alias dbreset='rake db:reset SYNC_FROM_STORMPATH=true'
alias spreset='rake db:reset RESET_STORMPATH=true'

alias js='npm test'
alias js-debug='npm run testdebug'

alias h='heroku'
alias hc='h run console -a'
alias hr='h releases -a'
alias qascale='h scale worker=1 scheduler=1 -a'
alias 0scale='h scale worker=0 scheduler=0 -a'
alias hsql='h pg:psql -a'

alias tm='tmux'
alias tmn='tmux new -s'
alias tma='tmux a -t'

alias filediff=gitFileDiff
gitFileDiff() {
  git diff-tree --no-commit-id --name-only -r HEAD..$1
}

#source ~/bin/git-completion.bash # run if not working

fpath=(~/.zsh $fpath)

